version: '3.3'

services:
  gobert-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gobert-client
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3123
      - CLAWDBOT_URL=ws://localhost:18789
      - CLAWDBOT_GATEWAY_TOKEN=${CLAWDBOT_GATEWAY_TOKEN}
    restart: unless-stopped
    env_file:
      - .env.local
